name: artemi_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
