name: artemi_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  animated_text_kit: ^4.2.3
  carousel_slider: ^5.0.0
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  flutter_pw_validator: ^1.6.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  numberpicker: ^2.1.2
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  sign_in_with_apple: ^7.0.1
  smooth_page_indicator: ^1.2.1
  uuid: ^4.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/splash_screen/

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo/logo.png
  adaptive_icon:
    background: "#000000"

flutter_native_splash:
  image: 'assets/splash_screen/splash.png'
  shimmer: null
  duration: 5
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  color: "#000000"
  web: false

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
